// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pabuvquuipcqftfculdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhYnV2cXV1aXBjcWZ0ZmN1bGRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODM4MDcsImV4cCI6MjA2NjQ1OTgwN30.WiunwV2O-v_BTrLbReenmKVY3_6cwlRjBZOtyQgAEX8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);